<?php

namespace AppBundle\Repository;

/**
 * AddClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddClassRepository extends \Doctrine\ORM\EntityRepository
{
}
