<?php

namespace AppBundle\Repository;

/**
 * AddLecturerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddLecturerRepository extends \Doctrine\ORM\EntityRepository
{
}
