<?php

namespace AppBundle\Repository;

/**
 * AddSubjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddSubjectRepository extends \Doctrine\ORM\EntityRepository
{
}
